### ISSUE TITLE
detect when a KeyboardEvent of type `keypress` is used as argument

### ISSUE THREAD

**Issue by dasilvacontin** [timoxley/keycode#18]
And act accordingly, giving the correct `keyCode`.

**Comment by timoxley** [comment]
+1 PR welcome.

**Comment by Aweary** [comment]
Is this issue still valid? It looks like the `searchInput && 'object' === typeof searchInput` check should also correctly parse instances of `KeyboardEvent`.

**Comment by timoxley** [comment]
Yep this appears fixed.
