### ISSUE TITLE
Exported External Package Typings File

### ISSUE THREAD

**Issue by cmj91uk** [timoxley/keycode#28]
Hi,

When importing the module via the ES6 import syntax using Visual Studio Code an error is displayed about the typings file.

"Exported external package typings file '/../node_modules/keycode/keycode.d.ts' is not a module. Please contact the package author to update the package definition"

It doesn't stop the compilation via Babel and just appears as an error within VSCode. However it would be nice to not have the error so that the handy Warnings and Errors panel can display 0 and 0 again.

Thanks in advance.

**Comment by timoxley** [comment]
@artfuldev any ideas?

**Comment by artfuldev** [comment]
Will look into this shortly
